# Generated by Django 3.0.5 on 2020-04-29 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_fname', models.CharField(max_length=50)),
                ('sta_lname', models.CharField(max_length=50)),
                ('sta_email', models.EmailField(max_length=254, unique=True)),
                ('sta_phone', models.CharField(max_length=10)),
                ('sta_position', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_fname', models.CharField(max_length=50)),
                ('cus_lname', models.CharField(max_length=50)),
                ('cus_email', models.EmailField(max_length=254, unique=True)),
                ('cus_phone', models.CharField(max_length=10)),
                ('cus_address', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
