# Generated by Django 3.0.5 on 2020-04-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('producer_name', models.CharField(max_length=255)),
                ('years', models.CharField(max_length=4)),
                ('data', models.TextField()),
                ('category', models.CharField(choices=[('EL', 'Electrical Line'), ('IL', 'Insuments Line'), ('TL', 'Tools Line'), ('MCL', 'Material Consumable Line'), ('SEL', 'Safety Equipment Line'), ('ILT', 'Insuments Line-Temperature'), ('ILF', 'Insuments Line-Flow Meter'), ('ITP', 'Insuments Line-Pressure'), ('AL', 'Accessoreis Line'), ('CL', 'Consumable Line')], max_length=3)),
                ('type', models.CharField(choices=[('BL', 'Business Line'), ('VI', 'Vision'), ('MI', 'Mission')], max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'มีสินค้า'), ('NO_AVAILABLE', 'ไม่มีสินค้า'), ('HIDE', 'ซ่อน')], max_length=12)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('promotion_code', models.CharField(max_length=8, unique=True)),
                ('discount_percent', models.FloatField()),
                ('minimum_cost', models.FloatField()),
                ('expire_day', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
