# Generated by Django 3.0.5 on 2020-04-30 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Manage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.IntegerField()),
                ('order_date', models.DateField(auto_now=True)),
                ('total_price', models.FloatField()),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.Customer')),
                ('sta_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('item_price', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Order.Order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Manage.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Picked', 'รับสินค้าเเล้ว'), ('Approved', 'ยืนยันคำสั่งซื้อ'), ('Denied', 'ปฎิเสษคำสั่งซื้อ'), ('Returned', 'คืนสินค้าเเล้ว'), ('Pending', 'รอการยืนยัน')], max_length=8)),
                ('total_price', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Manage.Product')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Manage.Promo')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(auto_now=True)),
                ('tex_id', models.CharField(max_length=255)),
                ('total_price', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Order.Order')),
            ],
        ),
    ]
